apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  storageClassName: nfs-server
  nfs:
    path: /srv/nfsshare
    server: 10.0.0.5
    readOnly: false
